base:
  random_state: 23
  target_col_name: class
  n_jobs: -1
  split_ratio: 0.1

logging_folder_paths:
  data: Logs/make_dataset.log
  features: Logs/preprocess_data.log
  model_creation: Logs/model_creation.log
  make_predictions: Logs/make_predictions.log

data:
  raw_data: Data/raw
  processed_data: Data/processed
  data_url_base: https://drive.google.com/uc?id=
  train_data_url: https://drive.google.com/file/d/1UiFmiaLmD4CKbXh9xWqiUCi-5Vq6ce3_/view?usp=sharing
  test_data_url: https://drive.google.com/file/d/1Q-YuLzD9M4d7cIcD48LzOJubSY9Poi5A/view?usp=sharing

model:
  preprocess_pipe_folderpath: Preprocessing_utilities
  preprocess_pipe_filename: preprocess_pipe.pkl
  label_encoder_filename: label_encoder.pkl
  rfc:
    max_depth: 3
    max_features: 130
    min_samples_split: 2
    min_samples_leaf: 1
  model_foldername: Models
  model_name: rfc.pkl

metrics_path:
  metrics_folder: Metrics
  metrics_file: metrics.json
  clf_report_filename: classification_report.csv

plots:
  plots_folder: Plots
  pr_thr_name: Precision_Recall_VS_Threshold.png
  pr_name: Precision_VS_Recall.png
  cm_name: confusion_matrix.png
