base:
  random_state:23


logging_folder_paths:
  data: Logs/make_dataset.log
  features: Logs/preprocess_data.log
  model_creation: Logs/model_creation.log
  model_evaluation: Logs/model_evaluation.log